<a href="https://colab.research.google.com/github/yashk1900/MLpractice/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [4]:
data = load_iris()
data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [5]:
X=data['data']
y=data['target']
column_names = data['feature_names']

In [7]:
X


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
X= pd.DataFrame(X,columns = column_names)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [16]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
147                6.5               3.0                5.2               2.0
2                  4.7               3.2                1.3               0.2
93                 5.0               2.3                3.3               1.0
119                6.0               2.2                5.0               1.5
..                 ...               ...                ...               ...
18                 5.7               3.8                1.7               0.3
45                 4.8               3.0                1.4               0.3
128                6.4               2.8                5.6               2.1
7                  5.0               3.4                1.5               0.2
15                 5.7               4.4                1.5               0.4

[112 rows x 4 columns]

In [15]:
y_train

array([2, 2, 0, 1, 2, 1, 2, 2, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 2, 1, 0, 1, 0, 2, 2, 2, 0, 0, 1, 2, 2, 0, 2, 1, 2, 0, 2, 2, 0,
       2, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1,
       2, 1, 2, 0, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 1, 0, 2, 0, 1,
       1, 2, 2, 1, 1, 0, 2, 1, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 1, 0, 0, 2,
       0, 0])

In [49]:
means = X_train.groupby(y_train).apply(np.mean)

In [50]:
means

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           5.035000          3.487500           1.472500            0.2575
1           5.891892          2.735135           4.218919            1.3000
2           6.574286          2.977143           5.525714            2.0200

In [51]:
stds = X_train.groupby(y_train).apply(np.std)

In [52]:
stds

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.343184          0.350847           0.173187          0.109287
1           0.519032          0.315557           0.485374          0.188880
2           0.644689          0.337288           0.485412          0.285657

In [53]:
probs  = X_train.groupby(y_train).apply(lambda x: len(x)) / X_train.shape[0]

In [54]:
probs

0    0.357143
1    0.330357
2    0.312500
dtype: float64

In [55]:
from scipy.stats import norm

In [66]:
y_pred=[]
for elem in range(X_test.shape[0]):
  p={}
  for cl in np.unique(y_train):
    p[cl] = probs.iloc[cl]
    # print(X_test.iloc[elem])
    for index,param in enumerate(X_test.iloc[elem]):
      p[cl]*=norm.pdf(param,means.iloc[cl,index],stds.iloc[cl,index])
  y_pred.append(pd.Series(p).values.argmax())


In [67]:
from sklearn.metrics import accuracy_score

In [68]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [71]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

accuracy_score(y_test,model.predict(X_test))

0.9473684210526315